Add Exporters to Prometheus #41
kitabisa/teler pull request #42
Opened 2020-10-30 22:31 UTC by JustHumanz

### Summary
- Add Exporters to Prometheus for monitoring in realtime and easy to analyze the log (#41)

### Proposed of changes

This PR fixes/implements the following **bugs/features**:
- Add Exporters to Prometheus

### How has this been tested?
Add -m/--metrics parameter for `Run as exporter`
Proof:
example query in prometheus
<img src="https://i.imgur.com/Hn0oZHF.png">

### Closing issues

Fixes #41 

### Checklist:

- [x] My code follows the code style of this project.
- [x] My change requires a change to the documentation.
  - [x] I have updated the documentation accordingly.
- [x] I have followed the guidelines in our [CONTRIBUTING.md](https://github.com/kitabisa/teler/blob/development/.github/CONTRIBUTING.md) document.
- [ ] I have written new tests for my changes.
  - [ ] My changes successfully ran and pass tests locally.

2020-10-30 22:43 UTC, dwisiswant0 commented
Can you please rebase it again from `master`, @JustHumanz?

2020-10-30 22:43 UTC, dwisiswant0 commented
/assign @JustHumanz

2020-10-30 23:51 UTC, dwisiswant0 requested changes
When I try to run it with command as:
```bash
> [buffers] | ./bin/teler -m -p
```
Program doesn't run port with the specified default value.

I see `-m` metric flag does nothing but mediate true/false logic.
It's better to be refactored as: `-m <PORT>`, if the `PORT` value isn't provided, then we run metric with the default value we specify.

I also saw you create a new function that was exported as `MetricInit`, it's also better if you create that function as a new package _(e.g. `metrics`)_, and not in `teler` package itself.

If you have rebased again, please revise the review as needed.
Thank you!

2020-10-30 23:51 UTC, dwisiswant0 commented on README.md
> +|`teler_threats_count_total`  | the total amount of threats     |
It should be: `Total number of detected threats`.

2020-10-30 23:51 UTC, dwisiswant0 commented on README.md
> +|`teler_cwa`                  | get all payload from `Common Web Attack` threats  |
It should be: `Get lists of Common Web Attacks`.

2020-10-30 23:51 UTC, dwisiswant0 commented on README.md
> +|`teler_badcrawler`           | list useragent and remote address of threats              |
It should be: `Get lists of Bad Crawler requests`.

2020-10-30 23:51 UTC, dwisiswant0 commented on README.md
> +|`teler_dir_bruteforce`       | list of bruteforced dir by threats          |
It should be: `Get lists of Directories Bruteforced`.

2020-10-30 23:51 UTC, dwisiswant0 commented on README.md
> +|`teler_badip_count`          | count of bad ip address       |
It should be: `Total number of Bad IP Addresses`.

2020-10-30 23:51 UTC, dwisiswant0 commented on README.md
> +|`teler_bad_referrer`         | http request with a bad referrer          |
It should be: `Get lists of Bad Referrer requests`.

2020-10-30 23:51 UTC, dwisiswant0 commented on internal/runner/runner.go
> +		log.Infof("Listening metrics on port : " + strconv.Itoa(options.MetricsPort))
Please remove trailing spaces for this.
```diff
-		log.Infof("Listening metrics on port : " + strconv.Itoa(options.MetricsPort))
+		log.Infof("Listening metrics on port: " + strconv.Itoa(options.MetricsPort))
```

2020-10-30 23:51 UTC, dwisiswant0 commented on pkg/teler/metrics.go
> +			Help: "teler_cwa show all cwa threats",
It should be: `Get lists of Common Web Attack threats`.

2020-10-30 23:51 UTC, dwisiswant0 commented on pkg/teler/metrics.go
> +			Help: "teler_badcrawler get a bad crawler",
It should be: `Get lists of Bad Crawler requests`.

2020-10-30 23:51 UTC, dwisiswant0 commented on pkg/teler/metrics.go
> +			Help: "teler_dir_bruteforce list of bruteforced dir",
It should be: `Get lists of Directories Bruteforced`.

2020-10-30 23:51 UTC, dwisiswant0 commented on pkg/teler/metrics.go
> +			Help: "get threats count",
It should be: `Total number of detected threats`.

2020-10-30 23:51 UTC, dwisiswant0 commented on pkg/teler/metrics.go
> +			Help: "get_badip remote address of threats",
It should be: `Total number of Bad IP Addresses`.

2020-10-30 23:51 UTC, dwisiswant0 commented on pkg/teler/metrics.go
> +			Help: "get a http with bad referrer",
It should be: `Get lists of Bad Referrer requests`.

2020-10-30 23:51 UTC, dwisiswant0 commented on cmd/teler/main.go
> +
Please remove trailing newline in this.

2020-10-30 23:51 UTC, dwisiswant0 commented on cmd/teler/main.go
> +
Please remove trailing newline in this.

2020-10-30 23:51 UTC, dwisiswant0 commented on pkg/teler/metrics.go
> +	getcwa = prometheus.NewCounterVec(
We use camelCase for naming convention, please change this to `getCWA`.

2020-10-30 23:51 UTC, dwisiswant0 commented on pkg/teler/metrics.go
> +	getbadcrawler = prometheus.NewCounterVec(
We use camelCase for naming convention, please change this to `getBadCrawler`.

2020-10-30 23:51 UTC, dwisiswant0 commented on pkg/teler/metrics.go
> +	getdirbruteforce = prometheus.NewCounterVec(
We use camelCase for naming convention, please change this to `getDirBruteforce`.

2020-10-30 23:51 UTC, dwisiswant0 commented on pkg/teler/metrics.go
> +	getbadreferrer = prometheus.NewCounterVec(
We use camelCase for naming convention, please change this to `getBadReferrer`.

2020-10-30 23:51 UTC, dwisiswant0 commented on pkg/teler/metrics.go
> +	getthreatstotal = prometheus.NewCounterVec(
We use camelCase for naming convention, please change this to `getThreatsTotal`.

2020-10-30 23:51 UTC, dwisiswant0 commented on pkg/teler/metrics.go
> +//add var to register
```diff
-//add var to register
+// MetricInit will register a metric with the specified variables
```

2020-10-31 07:18 UTC, JustHumanz commented
wha,thx for suggestion,gonna fix it

2020-10-31 08:29 UTC, dwisiswant0 commented
Looks like you haven't resolved everything I've asked for changes. Please re-check carefully, @JustHumanz.

2020-10-31 08:48 UTC, JustHumanz commented
> Looks like you haven't resolved everything I've asked for changes. Please re-check carefully, @JustHumanz.

all done,can you testing it?
i'm not very sure with my code ._.

2020-10-31 08:58 UTC, dwisiswant0 approved these changes

2020-10-31 09:06 UTC, dwisiswant0 commented
Since I need a little rework from this, I'm going to change the base branch to `development`.
I really appreciate your efforts to contribute to teler development, @JustHumanz. Accepting now!

2020-10-31 09:07 UTC, dwisiswant0 commented
@all-contributors please add @JustHumanz for code. :man_dancing:

2020-10-31 09:10 UTC, merged